name: dev

on: [workflow_dispatch, push, pull_request]

env:
  # Customizing build type
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: package-install
      run: |
        sudo apt-get -qq update
        sudo apt -qq install gfortran libopenmpi-dev

    - name: petsc-install
      run: |
        export PETSC_DIR=$HOME/petsc
        echo "PETSC_DIR=$HOME/petsc" >> $GITHUB_ENV
        git clone https://gitlab.com/petsc/petsc.git --branch v3.16.0 $PETSC_DIR
        cd $PETSC_DIR
        echo "Alquimia >> Configuring petsc"
        PETSC_ARCH=debug ./configure --with-mpi=1 --with-debugging=1 --with-shared-libraries=1 --download-fblaslapack=1 --download-hdf5=1
        echo "PETSC_ARCH=debug" >> $GITHUB_ENV
        echo "Alquimia >> Building petsc"
        make
        
    - name: pflotran-install
      run: |
        printenv PETSC_DIR
        printenv PETSC_ARCH
#        ls $PETSC_DIR/$PETSC_ARCH
#        ls $PETSC_DIR/$PETSC_ARCH/include
#        ls $PETSC_DIR/$PETSC_ARCH/lib
        ls $PETSC_DIR/$PETSC_ARCH/externalpackages/include
        export PFLOTRAN_DIR=$HOME/pflotran
        echo "PFLOTRAN_DIR=$HOME/pflotran" >> $GITHUB_ENV
        git clone https://bitbucket.org/pflotran/pflotran --branch v3.0.2 $PFLOTRAN_DIR
        cd $PFLOTRAN_DIR/src/pflotran
        echo "Building libpflotranchem.a"	
        make libpflotranchem.a

    - name: crunchflow-install
      run: |
        export CRUNCH_DIR=$HOME/crunchtope-dev
        echo "CRUNCH_DIR=$HOME/crunchtope-dev" >> $GITHUB_ENV
        git clone https://bitbucket.org/crunchflow/crunchtope-dev $CRUNCH_DIR
        cd $CRUNCH_DIR/source
        echo "Building libcrunchchem.a"
        make libcrunchchem.a

    - uses: actions/checkout@v2

    - name: configure
      run: |
        cd alquimia-dev
        mkdir install
        export ALQUIMIA_DIR=$PWD/install	  
        echo "ALQUIMIA_DIR=$PWD/install" >> $GITHUB_ENV
        mkdir build
        cd build
        cmake ..  -DCMAKE_INSTALL_PREFIX=$ALQUIMIA_DIR   -DCMAKE_C_COMPILER=`which mpicc`   -DCMAKE_CXX_COMPILER=`which mpicxx`   -DCMAKE_Fortran_COMPILER=`which mpif90`   -DCMAKE_BUILD_TYPE=Release   -DXSDK_WITH_PFLOTRAN=ON  -DTPL_PFLOTRAN_LIBRARIES=$PFLOTRAN_DIR/src/pflotran/libpflotranchem.a   -DTPL_PFLOTRAN_INCLUDE_DIRS=$PFLOTRAN_DIR/src/pflotran  -DXSDK_WITH_CRUNCHFLOW=ON   -DTPL_CRUNCHFLOW_LIBRARIES=$CRUNCH_DIR/source/libcrunchchem.a   -DTPL_CRUNCHFLOW_INCLUDE_DIRS=$CRUNCH_DIR/source   -DCMAKE_BUILD_TYPE=DEBUG   -DCMAKE_C_FLAGS="-W -Wall -Wextra"   -DCMAKE_CXX_FLAGS="-W -Wall -Wextra"   -DCMAKE_Fortran_FLAGS="-W -Wall -Wextra"

    - name: build
      run: |
        cd alquimia-dev/build
        make -j2

    - name: test
      run: |
        cd alquimia-dev/build
        make test